repos:
  - repo: local
    hooks:
      - id: pylint-pep-check
        name: 💅 Pylint PEP Check
        entry: uv run pylint
        language: system
        types: [python]
        files: \.py$
        verbose: true
        stages: [pre-push]
        args:
        - --fail-under=4
      - id: pytest
        name: 🧪 Run unit tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
        verbose: true
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.14
    hooks:
      - id: uv-lock
        name: 🔒 Check that your uv.lock is ok
      - id: uv-sync
        name: 🔄 Sync uv.lock with pyproject.toml
      - id: uv-export
        name: 💾  Export your requirements.txt based on uv.lock
        args: ['--frozen', '-o', 'requirements.txt', '--no-hashes']
        files: ^uv\.lock$
