name: build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install only the 'website' dependencies via PDM
        run: pdm install --group website

      - name: Configure GitHub credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_WRITE }}@github.com/${{ github.repository }}

      - name: Deploy with MkDocs
        run: pdm run mkdocs gh-deploy --force --clean --verbose