name: Promote PyLadies' anniversaries

on:
  schedule:
    - cron: '0 11 * * *' # runs every day at noon CET
  workflow_dispatch: # allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_WRITE }} # Uses PAT for checkout to handle protected branch
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checkout gallery content (person SOT)
        run: git clone --depth=1 https://github.com/cosimameyer/gallery.git gallery

      # - name: Execute Python script on Mastodon 🦣
      #   continue-on-error: true
      #   env:
      #     IMAGES: "anniversary_images"
      #     CLIENT_NAME: "pyladies_bot"
      #     GALLERY_PATH: "gallery/content/amazing-women-in-tech"
      #     ACCESS_TOKEN: ${{ secrets.PYLADIES_MASTODON_ACCESS_TOKEN }}
      #     CLIENT_ID: ${{ secrets.PYLADIES_MASTODON_CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.PYLADIES_MASTODON_CLIENT_SECRET }}
      #     PASSWORD: ${{ secrets.PYLADIES_MASTODON_PASSWORD }}
      #     USERNAME: ${{ secrets.PYLADIES_MASTODON_USERNAME }}
      #     BOT_CLIENTCRED_SECRET: ${{ secrets.PYLADIES_MASTODON_CLIENTCRED_SECRET }}
      #   run: python src/promote_anniversaries.py

      - name: Execute Python script on Bluesky 🦋
        env:
          IMAGES: "anniversary_images"
          CLIENT_NAME: "pyladies_bot"
          PLATFORM: "bluesky"
          GALLERY_PATH: "gallery/content/amazing-women-in-tech"
          PASSWORD: ${{ secrets.PYLADIES_BSKY_PASSWORD }}
          USERNAME: ${{ secrets.PYLADIES_BSKY_USERNAME }}
        run: python src/promote_anniversaries.py

      - name: Push changes
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.SECRET_WRITE }}
          commit-message: "Automated anniversary update"
          branch: bot/pyladies-anniversary-update
          delete-branch: true
          title: "Update PyLadies anniversary data"
          body: "Automated anniversary update."

      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.SECRET_WRITE }}
        run: gh pr merge --squash "${{ steps.cpr.outputs.pull-request-number }}" -R cosimameyer/community-bots