name: Boost posts that the tag pyladies

on:
    schedule:
    - cron: '5 */6 * * *' #'0 */12 * * *' 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9.16' # install the python version needed

        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # - name: Execute Python script for Mastodon 🦣
        #   env:
        #     PLATFORM: "mastodon"
        #     CLIENT_NAME: "pyladies_bot"
        #     ACCESS_TOKEN: ${{ secrets.PYLADIES_MASTODON_ACCESS_TOKEN }}
        #     CLIENT_ID: ${{ secrets.PYLADIES_MASTODON_CLIENT_ID }}
        #     CLIENT_SECRET: ${{ secrets.PYLADIES_MASTODON_CLIENT_SECRET }}
        #     PASSWORD: ${{ secrets.PYLADIES_MASTODON_PASSWORD }}
        #     USERNAME: ${{ secrets.PYLADIES_MASTODON_USERNAME }}
        #     RLADIES_MASTODON_CLIENTCRED_SECRET: ${{ secrets.PYLADIES_MASTODON_CLIENTCRED_SECRET }}
        #     TAGS_TO_BOOST: "pyladies"
        #   run: python src/boost_tags.py
        
        - name: Execute Python script for Bluesky 🦋
          env:
            PLATFORM: "bluesky"
            CLIENT_NAME: "pyladies_bot"
            PASSWORD: ${{ secrets.PYLADIES_BSKY_PASSWORD }}
            USERNAME: ${{ secrets.PYLADIES_BSKY_USERNAME }}
            TAGS_TO_BOOST: "pyladies"
          run: python src/boost_tags.py
