name: Promote PyLadies' libraries

on:
  schedule:
    - cron: '0 9 1-31/7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_WRITE }}
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Execute py script for Mastodon 🦣
      #   continue-on-error: true
      #   env:
      #     PLATFORM: "mastodon"
      #     COUNTER: "pyladies_packages_counter_mastodon.txt"
      #     JSON_FILE: "pyladies_packages_meta_data.json"
      #     CLIENT_NAME: "pyladies_bot"
      #     ACCESS_TOKEN: ${{ secrets.PYLADIES_MASTODON_ACCESS_TOKEN }}
      #     CLIENT_ID: ${{ secrets.PYLADIES_MASTODON_CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.PYLADIES_MASTODON_CLIENT_SECRET }}
      #     PASSWORD: ${{ secrets.PYLADIES_MASTODON_PASSWORD }}
      #     USERNAME: ${{ secrets.PYLADIES_MASTODON_USERNAME }}
      #     RLADIES_MASTODON_CLIENTCRED_SECRET: ${{ secrets.PYLADIES_MASTODON_CLIENTCRED_SECRET }}
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #   run: python src/promote_package.py

      - name: Execute py script for Bluesky 🦋
        env:
          PLATFORM: "bluesky"
          COUNTER: "pyladies_packages_counter_bluesky.txt"
          JSON_FILE: "pyladies_packages_meta_data.json"
          CLIENT_NAME: "pyladies_bot"
          PASSWORD: ${{ secrets.PYLADIES_BSKY_PASSWORD }}
          USERNAME: ${{ secrets.PYLADIES_BSKY_USERNAME }}
        run: python src/promote_package.py

      - name: Push changes
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.SECRET_WRITE }}
          commit-message: "Update PyLadies library counter metadata"
          branch: bot/pyladies-library-metadata
          delete-branch: true
          title: "Update PyLadies library counter metadata"
          body: "Automated update of library promotion counter."

      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.SECRET_WRITE }}
        run: gh pr merge --squash "${{ steps.cpr.outputs.pull-request-number }}" -R cosimameyer/community-bots
