name: Boost posts that the tag rladies

on:
    schedule:
    - cron: '0 */6 * * *' #'5 */12 * * *'
    workflow_dispatch:
        inputs:
            tags:
                description: 'Comma-separated tags to boost'
                default: 'rladies'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo content
          uses: actions/checkout@v7 # checkout the repository content

        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version-file: 'pyproject.toml'

        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # - name: Execute Python script for Mastodon 🦣
        #   env:
        #       PLATFORM: "mastodon"
        #       CLIENT_NAME: "rladies_bot"
        #       ACCESS_TOKEN: ${{ secrets.RLADIES_MASTODON_ACCESS_TOKEN }}
        #       CLIENT_ID: ${{ secrets.RLADIES_MASTODON_CLIENT_ID }}
        #       CLIENT_SECRET: ${{ secrets.RLADIES_MASTODON_CLIENT_SECRET }}
        #       PASSWORD: ${{ secrets.RLADIES_MASTODON_PASSWORD }}
        #       USERNAME: ${{ secrets.RLADIES_MASTODON_USERNAME }}
        #       RLADIES_MASTODON_CLIENTCRED_SECRET: ${{ secrets.RLADIES_MASTODON_CLIENTCRED_SECRET }}
        #       TAGS_TO_BOOST: "rladies"
        #   run: python src/boost_tags.py
          
        - name: Execute Python script for Bluesky 🦋
          env:
              PLATFORM: "bluesky"
              CLIENT_NAME: "rladies_bot"
              PASSWORD: ${{ secrets.RLADIES_BSKY_PASSWORD }}
              USERNAME: ${{ secrets.RLADIES_BSKY_USERNAME }}
              TAGS_TO_BOOST: ${{ github.event.inputs.tags || 'rladies' }}
          run: python src/boost_tags.py
