name: Boost posts that mention the R-Ladies' bot

on:
  schedule:
    - cron: '55 */6 * * *' #'0 6 1-31/2 * *' # only run on even days '0 7 */2 * *' #'0 0 1 * *'  # "At 07:00 UTC every second day (which is 10 CET)"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Execute Python script for Mastodon 🦣
      #   env:
      #     PLATFORM: "mastodon"
      #     CLIENT_NAME: "rladies_bot"
      #     ACCESS_TOKEN: ${{ secrets.RLADIES_MASTODON_ACCESS_TOKEN }}
      #     CLIENT_ID: ${{ secrets.RLADIES_MASTODON_CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.RLADIES_MASTODON_CLIENT_SECRET }}
      #     PASSWORD: ${{ secrets.RLADIES_MASTODON_PASSWORD }}
      #     USERNAME: ${{ secrets.RLADIES_MASTODON_USERNAME }}
      #     RLADIES_MASTODON_CLIENTCRED_SECRET: ${{ secrets.RLADIES_MASTODON_CLIENTCRED_SECRET }}
      #   run: python src/boost_mentions.py

      - name: Execute Python script for Bluesky 🦋
        env:
          PLATFORM: "bluesky"
          CLIENT_NAME: "rladies_bot"
          PASSWORD: ${{ secrets.RLADIES_BSKY_PASSWORD }}
          USERNAME: ${{ secrets.RLADIES_BSKY_USERNAME }}
        run: python src/boost_mentions.py
